### ISSUE TITLE
Can't run script from within QuickPython on Windows

### ISSUE THREAD

**Issue by donno** [timothycrosley/quickpython#1]
### Steps to reproduce

1. Install quickpython on Windows
1. Start quickpython
1. Go to the example menu and open one of the scripts
1. Press F5

### Expected behavior
The script is ran.

### Actual behavior 
The following error message appears:
```
'PYTHONBREAKPOINT' is not recognized as an internal or external command,
operable program or batch file.
```

### Suspected cause
The issue is Microsoft Windows doesn't accept the practice of  ```NAME=value program arguments``` as defining an environment variable called NAME with the given value before running a program.

The statement in question is:
https://github.com/timothycrosley/quickpython/blob/01072f43eb8aa454d9070d04f4444396d9a83eab/quickpython/cli.py#L356-L358

**Comment by timothycrosley** [comment]
Thanks for reporting this issue! This should be resolved in the just released 0.1.2 release of quickpython

~Timothy
